using System;
using Xunit;

namespace Autogenerated.Tests
{
  public class Class2Test
  {
    [Fact]
    public void Method1Test()
    {
      Assert.True(false, "autogenerated");
    }

    [Fact]
    public void Method2Test()
    {
      Assert.True(false, "autogenerated");
    }

  }
}